version = 3.9.10
runner.dialect = scala3future
maxColumn = 100
align.preset=none
rewrite.trailingCommas.style = always
newlines.selectChains.style = keep
newlines.selectChains.classicKeepAfterFirstBreak = true
project.excludePaths = ["glob:**/.idea/fileTemplates/*.scala", "glob:**/.idea/fileTemplates/includes/*.scala"]