name: Publish Library to GCP
on:
  push:
    tags:
      - 'v*' # Triggers on tags starting with 'v', like v1.0.0 or v2.1.3-rc1

jobs:
  aot-compile:
    name: AOT compile on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, ubuntu-22.04, ubuntu-22.04-arm]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Cache Dependencies
        uses: coursier/cache-action@v8

      - name: Setup JVM and Mill
        uses: coursier/setup-action@v3
        with:
          jvm: temurin:17 # The minimal JDK version for Scala Next
          apps: mill

      - name: Build Native Executable with Mill
        run: ./mill cli.jvm.nativeImage # Now Mill will find 'cs' automatically, fetch GraalVM, and compile

      - name: Smoke Tests for Executable
        run: |
          OUTPUT=$(./out/cli/jvm/nativeImage.dest/linkml-scala validate metamodel/resources/meta.yaml)
          echo "$OUTPUT"
          if ! echo "$OUTPUT" | grep -q "Schema is valid."; then
            echo "Error: Expected success message not found."
            exit 1 # Forces the GitHub Action step to fail
          fi

      - name: Upload Binary
        uses: actions/upload-artifact@v7
        with:
          name: linkml-scala-${{ matrix.os }}
          path: out/cli/jvm/nativeImage.dest/*

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - aot-compile

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Required so Mill can see the full Git history and tags
          submodules: recursive

      - name: Cache Dependencies
        uses: coursier/cache-action@v8

      - name: Setup JVM and Mill
        uses: coursier/setup-action@v3
        with:
          jvm: temurin:17 # The minimal JDK version for Scala Next
          apps: mill

      - name: Publish Artifacts to GCP
        env:
          GCP_MAVEN_REPO: ${{ secrets.GCP_MAVEN_REPO }}
          GCP_MAVEN_RW: ${{ secrets.GCP_MAVEN_RW }}
        run: |
          export MILL_MAVEN_USERNAME="_json_key_base64"
          export MILL_MAVEN_PASSWORD="$GCP_MAVEN_RW"          
          ./mill mill.javalib.MavenPublishModule/publishAll \
            --publishArtifacts __.publishArtifacts \
            --releaseUri "$GCP_MAVEN_REPO" \
            --snapshotUri "$GCP_MAVEN_REPO" \

      - name: Assembly Uber-JAR
        run: |
          ./mill cli.jvm.assembly
          mv out/cli/jvm/assembly.dest/*.jar linkml-scala.jar

      - name: Upload Uber-JAR
        uses: actions/upload-artifact@v7
        with:
          name: linkml-scala-assembly
          path: linkml-scala.jar

      - name: Download Binaries
        uses: actions/download-artifact@v8
        with:
          pattern: linkml-scala-*
          path: bin
          
      - name: Rename Binaries
        run: |
          mv bin/linkml-scala-assembly/linkml-scala.jar linkml-scala.jar
          mv bin/linkml-scala-macos-14/linkml-scala linkml-scala-mac-arm64
          mv bin/linkml-scala-ubuntu-22.04/linkml-scala linkml-scala-linux-x86_64
          mv bin/linkml-scala-ubuntu-22.04-arm/linkml-scala linkml-scala-linux-arm64
          chmod +x linkml-scala-mac-arm64
          chmod +x linkml-scala-linux-x86_64
          chmod +x linkml-scala-linux-arm64

      - name: Create Gzipped Versions
        run: |
          gzip -9 -k linkml-scala-mac-arm64 &
          gzip -9 -k linkml-scala-linux-x86_64 &
          gzip -9 -k linkml-scala-linux-arm64 &
          wait

      - name: Upload Binaries
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: "${{ github.ref_name }}"
          name: "${{ github.ref_name }}"
          artifacts: linkml-scala*
          generateReleaseNotes: false
          allowUpdates: true
          replacesArtifacts: true
