name: Build & test

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-ci-pr-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            java: 17
          - os: ubuntu-latest
            java: 25
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 256 # limits number of snapshots between releases
          fetch-tags: true # forces GitHub to fetch tags even on a partial history

      - name: Cache dependencies
        uses: coursier/cache-action@v8

      - name: Setup JVM and Mill
        uses: coursier/setup-action@v3
        with:
          jvm: temurin:${{ matrix.java }}
          apps: mill

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup uv/python
        uses: astral-sh/setup-uv@v8.2.0
        with:
          activate-environment: true

      - name: Install LinkML-py and generate cross-test models
        run: |
          uv pip install linkml
          python cross_test.py 

      - name: Build and test
        run: |
          ./mill --no-server -j 0 __.test

      - name: Re-generate the metamodel and check if it's unchanged
        run: |
          cp -r metamodel/ metamodel_prev/
          ./mill --no-server cli.jvm.run generate scala --to metamodel/src/eu/neverblink/linkml/metamodel/ linkml:meta
          ./mill --no-server metamodel.jvm.fix
          ./mill --no-server metamodel.jvm.reformat
          diff -r metamodel metamodel_prev
          
      - name: Publish Snapshot to Sonatype Central
        if: matrix.java == 17 && github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          MILL_SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MILL_SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: |
          ./mill mill.javalib.SonatypeCentralPublishModule/    
